# -*- coding: utf-8 -*-
"""apriori.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t2y3RTowI1Jjof5N1CFYdx4y2B5AGFMg
"""

product =["P1", "P2", "P3", "P4", "P5"]

import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

cd 'drive/My Drive/Colab Notebooks'

trans_tbl = pd.read_csv('Transaction_table.csv')

transaction_table = {
    'T-ID': ["T10", "T20", "T30", "T40","T50", "T60","T70", "T80","T90"],
    'Products(P)':[("P1", "P2", "P5"),("P2", "P4"),("P2", "P3"),("P1", "P2", "P4"),("P1", "P3"),("P2", "P3"),("P1", "P3"),("P1", "P2", "P3","P5"),("P1", "P2", "P3")]
}
trans_tbl = pd.DataFrame(transaction_table)
trans_tbl

my_result = []
temp = set()
for inner in trans_tbl:
   for elem in inner:
      if not elem in temp:
         temp.add(elem)
         my_result.append(elem)
print("The unique elements in the list of tuples are : ")
print(my_result)

for i in range(len(trans_tbl['T-ID'])):
  #print(i)
  print(trans_tbl['Products(P)'][i])
  for j in range(len(trans_tbl['Products(P)'][i][j])):
    print(j)
    print(trans_tbl['Products(P)'][i][j])

for j in range(len(trans_tbl['Products(P)'])):
    print(j)
    print(trans_tbl['Products(P)'][j])

print("2" in trans_tbl['Products(P)'][2])

prod = list(map(set,trans_tbl['Products(P)'].values))
prod

for i in range(5):
  print(i)
  if (bool(str(i) in trans_tbl['Products(P)'][i]) == True):
    print(trans_tbl['Products(P)'][i])
    i+=1

prod = trans_tbl['Products(P)'].values
prod