# -*- coding: utf-8 -*-
"""Cluster_Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14qB7rUcZe8IB_tf-2c0OfqH4p4MfqXLD
"""

import pandas as pd
import numpy as np
from sklearn.datasets import make_blobs

dataset = make_blobs(n_samples =200, centers =4, n_features =2, cluster_std =1.6, random_state =50)

from sklearn.cluster import KMeans

points = dataset[0]
kmeans =KMeans(n_clusters =4)
kmeans.fit(points)

import matplotlib.pyplot as plt

plt.scatter(dataset[0][:,0], dataset[0][:,1])

clusters =kmeans.cluster_centers_
print(cluster)

y_km =kmeans.fit_predict(points)
y_km

plt.scatter(points[y_km==0,0], points[y_km == 0, 1], s=50, color ='red')
plt.scatter(points[y_km==1,0], points[y_km == 1, 1], s=50, color ='blue')
plt.scatter(points[y_km==2,0], points[y_km == 2, 1], s=50, color ='yellow')
plt.scatter(points[y_km==3,0], points[y_km == 3, 1], s=50, color ='green')

plt.scatter(clusters[0][0], clusters[0][1], marker='*', color ='black')
plt.scatter(clusters[1][0], clusters[1][1], marker='*', color ='black')
plt.scatter(clusters[2][0], clusters[2][1], marker='*', color ='black')
plt.scatter(clusters[3][0], clusters[3][1], marker='*', color ='black')
plt.show()

